apiRules:
- include:
    uidRegex: ^nickmaltbie\.NetworkStateMachineUnity
    type: Namespace
- include:
    uidRegex: ^nickmaltbie\.NetworkStateMachineUnity\.*
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace